# config/deploy.yml
service: my_todo_app
image: juuh42dias/my_todo_app
servers:
  web:
    - 31.220.87.82
proxy:
  ssl: true
  host: labs.juliana.dev
ssh:
  user: kamal
registry:
  server: docker.io
  username: juuh42dias
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: my_todo_app-db
    DB_NAME: my_todo_app_production
    DB_USER: my_todo_app
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD

builder:
  arch: amd64

accessories:
  db:
    image: postgres:17
    host: 31.220.87.82
    env:
      clear:
        POSTGRES_DB: my_todo_app_production
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data